# golangci-lint run
name: golangci-lint
on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  golangci:
    name: lint-codebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: "1.22.5"
      - uses: actions/checkout@v4.1.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.54
          args: --timeout 15m0s --verbose --out-${NO_FUTURE}format tab
